# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20190514.0.0"

  config.vm.network "forwarded_port", guest: 5500, host: 5500

  # MORALIS_PROJECT_PATH should point to path of this project
  if ENV['MORALIS_PROJECT_PATH']
    config.vm.synced_folder ENV['MORALIS_PROJECT_PATH'], "/home/vagrant/project/"
  end

  # TODO add ansible provisioning option
  config.vm.provision "shell", path: "provision.sh", privileged: false
end
